In [4]:
#Decision Snippet Features for samples of random forest of threshold 1.


dataSet='adult'
rf_depth = 5
samples_count = 10

import csv,operator,sys,os
import numpy as np
import sklearn
import json
import FeatureGenerators.ReadData
import time
from functools import reduce
from statistics import mean, stdev
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.utils.estimator_checks import check_estimator
from sklearn.metrics import accuracy_score

sys.path.append('arch-forest/data/adult/')
sys.path.append('arch-forest/data/bank/')
sys.path.append('arch-forest/data/wine-quality/')
sys.path.append('arch-forest/data/')
sys.path.append('arch-forest/code/')
import trainForest
import Tree

import FeatureGenerators.DecisionSnippetFeatures

dataPath = "../frequentTreesInRandomForests/arch-forest/data/"
frequentTreesPath = "../frequentTreesInRandomForests/forests/rootedFrequentTrees/"
resultsPath = "../frequentTreesInRandomForests/forests/rootedFrequentTrees/"



#import train data
from FeatureGenerators.ReadData import readDataAdult,readDataBank, readWine, readWineTest, readDataSpambase

if (dataSet == 'adult'):
    X_train,Y_train = FeatureGenerators.ReadData.readDataAdult('train')
    X_test,Y_test = FeatureGenerators.ReadData.readDataAdult('test')
if (dataSet == 'spambase'):
    X_train,Y_train = FeatureGenerators.ReadData.readDataSpambase('train')
    X_test,Y_test = FeatureGenerators.ReadData.readDataSpambase('test')        
if (dataSet == 'letter'):
    X_train,Y_train = FeatureGenerators.ReadData.readDataLetter('train')
    X_test,Y_test = FeatureGenerators.ReadData.readDataLetter('test')  
if (dataSet == 'bank'):
    X_train,Y_train = FeatureGenerators.ReadData.readDataBank('train')
    X_test,Y_test = FeatureGenerators.ReadData.readDataBank('test')
if (dataSet == 'wine-quality'):
        X_train,Y_train = ReadData.readWine()
        X_test,Y_test = ReadData.readWineTest()




# Classification

    
results_list = []
time_list = []

scoring_function = 'accuracy'
pattern_max_size=6
variant = 'NoLeafEdges'

scores_list = []


for sample in range(0,samples_count):
    
    rootedFrequentTrees = "RF_"+str(rf_depth)+"_t1_"+str(sample+1)
    f = open(frequentTreesPath+dataSet+'/'+variant+'/leq'+str(pattern_max_size)+'/Samples/RF_'+str(rf_depth)+'/'+rootedFrequentTrees+'.json')
    frequentpatterns = json.load(f)
    f.close()

    dsf = FeatureGenerators.DecisionSnippetFeatures.FrequentSubtreeFeatures(map(lambda x: x['pattern'], frequentpatterns[-100:]))
       
    fts = dsf.fit_transform(X_train,0)

    from sklearn.preprocessing import OneHotEncoder
    fts_onehot = OneHotEncoder(n_values=dsf.get_n_values()).fit_transform(fts)

    



    model = GaussianNB()
    fts_onehot_nb_cv_score = cross_val_score(model, fts_onehot.toarray(), Y_train, cv=5, scoring=scoring_function)
   
    print(fts_onehot_nb_cv_score)
    dsf_score = fts_onehot_nb_cv_score.mean()
    scores_list.append(dsf_score)
    print(scores_list)
    print('DSF_'+str(sample+1)+ ': '+str(dsf_score))
    
    
    
    result = "t1_"+str(sample+1)+","+str(dsf_score)+",\n"
    results_list.append(result)
   

f= open(resultsPath+dataSet+'/Results_'+variant+'/leq'+str(pattern_max_size)+'/'+'RF_'+str(rf_depth)+'_'+scoring_function+'_Samples'+'.csv',"w")
for line in results_list:
    f.write(line)
f.write('\n')
f.write('Average: ,'+str(mean(scores_list))+'\n')
f.write('Deviation: ,'+str(stdev(scores_list)))
    
f.close()


10972


/home/falkhoury/anaconda3/envs/py3k/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:373: DeprecationWarning: Passing 'n_values' is deprecated in version 0.20 and will be removed in 0.22. You can use the 'categories' keyword instead. 'n_values=n' corresponds to 'categories=[range(n)] * n_features'.
  warnings.warn(msg, DeprecationWarning)


[0.7453303  0.73667426 0.74259681 0.76116682 0.75968992]
[0.7490916215638777]
DSF_1: 0.7490916215638777


/home/falkhoury/anaconda3/envs/py3k/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:373: DeprecationWarning: Passing 'n_values' is deprecated in version 0.20 and will be removed in 0.22. You can use the 'categories' keyword instead. 'n_values=n' corresponds to 'categories=[range(n)] * n_features'.
  warnings.warn(msg, DeprecationWarning)


[0.74259681 0.73257403 0.75671982 0.75341841 0.75786594]
[0.7490916215638777, 0.7486350023041459]
DSF_2: 0.7486350023041459


/home/falkhoury/anaconda3/envs/py3k/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:373: DeprecationWarning: Passing 'n_values' is deprecated in version 0.20 and will be removed in 0.22. You can use the 'categories' keyword instead. 'n_values=n' corresponds to 'categories=[range(n)] * n_features'.
  warnings.warn(msg, DeprecationWarning)


[0.69886105 0.70159453 0.68838269 0.70328168 0.71181031]
[0.7490916215638777, 0.7486350023041459, 0.7007860503223997]
DSF_3: 0.7007860503223997


/home/falkhoury/anaconda3/envs/py3k/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:373: DeprecationWarning: Passing 'n_values' is deprecated in version 0.20 and will be removed in 0.22. You can use the 'categories' keyword instead. 'n_values=n' corresponds to 'categories=[range(n)] * n_features'.
  warnings.warn(msg, DeprecationWarning)


[0.71207289 0.70933941 0.69886105 0.71330902 0.72093023]
[0.7490916215638777, 0.7486350023041459, 0.7007860503223997, 0.7109025211380162]
DSF_4: 0.7109025211380162


/home/falkhoury/anaconda3/envs/py3k/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:373: DeprecationWarning: Passing 'n_values' is deprecated in version 0.20 and will be removed in 0.22. You can use the 'categories' keyword instead. 'n_values=n' corresponds to 'categories=[range(n)] * n_features'.
  warnings.warn(msg, DeprecationWarning)


[0.72482916 0.72938497 0.74259681 0.74658159 0.75877793]
[0.7490916215638777, 0.7486350023041459, 0.7007860503223997, 0.7109025211380162, 0.7404340899722731]
DSF_5: 0.7404340899722731


/home/falkhoury/anaconda3/envs/py3k/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:373: DeprecationWarning: Passing 'n_values' is deprecated in version 0.20 and will be removed in 0.22. You can use the 'categories' keyword instead. 'n_values=n' corresponds to 'categories=[range(n)] * n_features'.
  warnings.warn(msg, DeprecationWarning)


[0.71753986 0.73211845 0.72118451 0.7379216  0.75193798]
[0.7490916215638777, 0.7486350023041459, 0.7007860503223997, 0.7109025211380162, 0.7404340899722731, 0.7321404826946121]
DSF_6: 0.7321404826946121


/home/falkhoury/anaconda3/envs/py3k/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:373: DeprecationWarning: Passing 'n_values' is deprecated in version 0.20 and will be removed in 0.22. You can use the 'categories' keyword instead. 'n_values=n' corresponds to 'categories=[range(n)] * n_features'.
  warnings.warn(msg, DeprecationWarning)


[0.74396355 0.73394077 0.75489749 0.76891522 0.76060192]
[0.7490916215638777, 0.7486350023041459, 0.7007860503223997, 0.7109025211380162, 0.7404340899722731, 0.7321404826946121, 0.7524637921689026]
DSF_7: 0.7524637921689026


/home/falkhoury/anaconda3/envs/py3k/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:373: DeprecationWarning: Passing 'n_values' is deprecated in version 0.20 and will be removed in 0.22. You can use the 'categories' keyword instead. 'n_values=n' corresponds to 'categories=[range(n)] * n_features'.
  warnings.warn(msg, DeprecationWarning)


[0.71617312 0.71252847 0.71343964 0.72470374 0.74281806]
[0.7490916215638777, 0.7486350023041459, 0.7007860503223997, 0.7109025211380162, 0.7404340899722731, 0.7321404826946121, 0.7524637921689026, 0.7219326049979387]
DSF_8: 0.7219326049979387


/home/falkhoury/anaconda3/envs/py3k/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:373: DeprecationWarning: Passing 'n_values' is deprecated in version 0.20 and will be removed in 0.22. You can use the 'categories' keyword instead. 'n_values=n' corresponds to 'categories=[range(n)] * n_features'.
  warnings.warn(msg, DeprecationWarning)


[0.70159453 0.70113895 0.70751708 0.70692799 0.7127223 ]
[0.7490916215638777, 0.7486350023041459, 0.7007860503223997, 0.7109025211380162, 0.7404340899722731, 0.7321404826946121, 0.7524637921689026, 0.7219326049979387, 0.7059801706224927]
DSF_9: 0.7059801706224927


/home/falkhoury/anaconda3/envs/py3k/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:373: DeprecationWarning: Passing 'n_values' is deprecated in version 0.20 and will be removed in 0.22. You can use the 'categories' keyword instead. 'n_values=n' corresponds to 'categories=[range(n)] * n_features'.
  warnings.warn(msg, DeprecationWarning)


[0.71480638 0.70888383 0.70615034 0.71285324 0.73096215]
[0.7490916215638777, 0.7486350023041459, 0.7007860503223997, 0.7109025211380162, 0.7404340899722731, 0.7321404826946121, 0.7524637921689026, 0.7219326049979387, 0.7059801706224927, 0.7147311870196541]
DSF_10: 0.7147311870196541


4
1.0
